repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args: ['--extra-keys', 'metadata.widgets metadata.vscode cell.metadata.execution']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: ['--fix']
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: local
    hooks:
      - id: check-models
        name: Check Claude model usage
        entry: python scripts/check_models.py
        language: python
        files: '\.ipynb$'
        pass_filenames: false
      
      - id: validate-notebooks
        name: Validate notebook structure
        entry: python scripts/validate_notebooks.py
        language: python
        files: '\.ipynb$'
        pass_filenames: false