name: Claude Model Check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'skills/**/*.ipynb'
      - '**.py'
      - '**.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  model-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Claude Model Validation
        uses: anthropics/claude-code-action@v1
        with:
          use_sticky_comment: true
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          timeout_minutes: "5"
          experimental_slash_commands_dir: ${{ github.workspace }}/.github/slash-commands
          prompt: "/model-check"